#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Dec 17, 2020 12:19:55 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import course_coordinator_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Course_coordinator (root)
    course_coordinator_support.init(root, top)
    root.mainloop()

w = None
def create_Course_coordinator(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Course_coordinator(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Course_coordinator (w)
    course_coordinator_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Course_coordinator():
    global w
    w.destroy()
    w = None

class Course_coordinator:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1920x1001+345+116")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Course Co-ordinator")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.023, rely=0.024, relheight=0.937
                , relwidth=0.954)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#8080ff")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.364, rely=0.038, height=31, width=418)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#00ff00")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''WELCOME COURSE CO-ORDINATOR''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.251, rely=0.127, height=31, width=225)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''COURSE CODE :''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.251, rely=0.217, height=31, width=223)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''COURSE TITLE :''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.251, rely=0.306, height=31, width=225)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''NO. OF CREDITS :''')

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.421, rely=0.127, relheight=0.043, relwidth=0.245)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.421, rely=0.217, relheight=0.043, relwidth=0.546)

        self.Text2.configure(background="white")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="blue")
        self.Text2.configure(selectforeground="white")
        self.Text2.configure(wrap="word")

        self.Text3 = tk.Text(self.Frame1)
        self.Text3.place(relx=0.42, rely=0.299, relheight=0.044, relwidth=0.084)
        self.Text3.configure(background="white")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="#d9d9d9")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="blue")
        self.Text3.configure(selectforeground="white")
        self.Text3.configure(wrap="word")

        self.addbtn = tk.Button(self.Frame1)
        self.addbtn.place(relx=0.413, rely=0.471, height=33, width=156)
        self.addbtn.configure(activebackground="#ececec")
        self.addbtn.configure(activeforeground="#000000")
        self.addbtn.configure(background="#d9d9d9")
        self.addbtn.configure(disabledforeground="#a3a3a3")
        self.addbtn.configure(foreground="#000000")
        self.addbtn.configure(highlightbackground="#d9d9d9")
        self.addbtn.configure(highlightcolor="black")
        self.addbtn.configure(pady="0")
        self.addbtn.configure(text='''ADD COURSE''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.409, rely=0.661, height=31, width=202)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''ENTER COURSE CODE :''')

        self.Text4 = tk.Text(self.Frame1)
        self.Text4.place(relx=0.381, rely=0.726, relheight=0.042, relwidth=0.181)

        self.Text4.configure(background="white")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="#d9d9d9")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="blue")
        self.Text4.configure(selectforeground="white")
        self.Text4.configure(wrap="word")

        self.removebtn = tk.Button(self.Frame1)
        self.removebtn.place(relx=0.426, rely=0.8, height=33, width=146)
        self.removebtn.configure(activebackground="#ececec")
        self.removebtn.configure(activeforeground="#000000")
        self.removebtn.configure(background="#d9d9d9")
        self.removebtn.configure(disabledforeground="#a3a3a3")
        self.removebtn.configure(foreground="#000000")
        self.removebtn.configure(highlightbackground="#d9d9d9")
        self.removebtn.configure(highlightcolor="black")
        self.removebtn.configure(pady="0")
        self.removebtn.configure(text='''REMOVE COURSE''')

        self.logoutbtn = tk.Button(self.Frame1)
        self.logoutbtn.place(relx=0.899, rely=0.025, height=33, width=96)
        self.logoutbtn.configure(activebackground="#ececec")
        self.logoutbtn.configure(activeforeground="#000000")
        self.logoutbtn.configure(background="#d9d9d9")
        self.logoutbtn.configure(disabledforeground="#a3a3a3")
        self.logoutbtn.configure(foreground="#000000")
        self.logoutbtn.configure(highlightbackground="#d9d9d9")
        self.logoutbtn.configure(highlightcolor="black")
        self.logoutbtn.configure(pady="0")
        self.logoutbtn.configure(text='''LOGOUT''')

if __name__ == '__main__':
    vp_start_gui()





