#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Nov 27, 2020 08:37:22 AM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1529x948+207+27
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background #8080ff -height 826 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1466 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #00ff00 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {AUTOMATIC EXAM FORM FILLER} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex48 \
        -background white -font TkTextFont -foreground black -height 39 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 295 -wrap word 
    $site_3_0.tex48 configure -font "TkTextFont"
    $site_3_0.tex48 insert end text
    vTcl:DefineAlias "$site_3_0.tex48" "Text1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {FILL FORM} -width 96 
    vTcl:DefineAlias "$site_3_0.but49" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ENTER USN : } 
    vTcl:DefineAlias "$site_3_0.lab50" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {NAME :} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {USN :} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {SEMESTER :} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {DEPARTMENT :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ADDRESS :} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {CGPA :} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {COURSES :} 
    vTcl:DefineAlias "$site_3_0.lab58" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {LAB COURSES :} 
    vTcl:DefineAlias "$site_3_0.lab59" "Label10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {EXAM FEE :} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Choose Exam Centre :} 
    vTcl:DefineAlias "$site_3_0.lab68" "Label19" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {SUBMIT FORM & GENERATE HALL TICKET} 
    vTcl:DefineAlias "$site_3_0.but73" "Button2" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis45 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 29 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 295 
    $site_3_0.lis45 configure -font "TkFixedFont"
    $site_3_0.lis45 insert end text
    vTcl:DefineAlias "$site_3_0.lis45" "Listbox11" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 27 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 292 
    $site_3_0.lis46 configure -font "TkFixedFont"
    $site_3_0.lis46 insert end text
    vTcl:DefineAlias "$site_3_0.lis46" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis47 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 28 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 295 
    $site_3_0.lis47 configure -font "TkFixedFont"
    $site_3_0.lis47 insert end text
    vTcl:DefineAlias "$site_3_0.lis47" "Listbox2" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 28 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 293 
    $site_3_0.lis48 configure -font "TkFixedFont"
    $site_3_0.lis48 insert end text
    vTcl:DefineAlias "$site_3_0.lis48" "Listbox3" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 78 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 294 
    $site_3_0.lis49 configure -font "TkFixedFont"
    $site_3_0.lis49 insert end text
    vTcl:DefineAlias "$site_3_0.lis49" "Listbox4" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 36 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 294 
    $site_3_0.lis50 configure -font "TkFixedFont"
    $site_3_0.lis50 insert end text
    vTcl:DefineAlias "$site_3_0.lis50" "Listbox5" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 40 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 165 
    $site_3_0.lis51 configure -font "TkFixedFont"
    $site_3_0.lis51 insert end text
    vTcl:DefineAlias "$site_3_0.lis51" "Listbox6" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 40 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 164 
    $site_3_0.lis52 configure -font "TkFixedFont"
    $site_3_0.lis52 insert end text
    vTcl:DefineAlias "$site_3_0.lis52" "Listbox7" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 38 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 153 
    $site_3_0.lis53 configure -font "TkFixedFont"
    $site_3_0.lis53 insert end text
    vTcl:DefineAlias "$site_3_0.lis53" "Listbox8" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 39 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 154 
    $site_3_0.lis54 configure -font "TkFixedFont"
    $site_3_0.lis54 insert end text
    vTcl:DefineAlias "$site_3_0.lis54" "Listbox9" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 41 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 164 
    $site_3_0.lis55 configure -font "TkFixedFont"
    $site_3_0.lis55 insert end text
    vTcl:DefineAlias "$site_3_0.lis55" "Listbox10" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 38 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 156 
    $site_3_0.lis56 configure -font "TkFixedFont"
    $site_3_0.lis56 insert end text
    vTcl:DefineAlias "$site_3_0.lis56" "Listbox12" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 39 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 163 
    $site_3_0.lis57 configure -font "TkFixedFont"
    $site_3_0.lis57 insert end text
    vTcl:DefineAlias "$site_3_0.lis57" "Listbox13" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 38 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 154 
    $site_3_0.lis58 configure -font "TkFixedFont"
    $site_3_0.lis58 insert end text
    vTcl:DefineAlias "$site_3_0.lis58" "Listbox14" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis59 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 38 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 164 
    $site_3_0.lis59 configure -font "TkFixedFont"
    $site_3_0.lis59 insert end text
    vTcl:DefineAlias "$site_3_0.lis59" "Listbox15" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis60 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 38 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 154 
    $site_3_0.lis60 configure -font "TkFixedFont"
    $site_3_0.lis60 insert end text
    vTcl:DefineAlias "$site_3_0.lis60" "Listbox16" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis61 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 38 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 164 
    $site_3_0.lis61 configure -font "TkFixedFont"
    $site_3_0.lis61 insert end text
    vTcl:DefineAlias "$site_3_0.lis61" "Listbox17" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis62 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 38 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 155 
    $site_3_0.lis62 configure -font "TkFixedFont"
    $site_3_0.lis62 insert end text
    vTcl:DefineAlias "$site_3_0.lis62" "Listbox18" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 28 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -width 164 
    $site_3_0.lis63 configure -font "TkFixedFont"
    $site_3_0.lis63 insert end text
    vTcl:DefineAlias "$site_3_0.lis63" "Listbox19" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {RVCE, Banglore} 
    vTcl:DefineAlias "$site_3_0.rad64" "rvcerb" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {PESET, Banglore} 
    vTcl:DefineAlias "$site_3_0.rad65" "pesetrb" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {RRCE, Banglore.} 
    vTcl:DefineAlias "$site_3_0.rad66" "rrcerb" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #808040 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Enter Fee Recipt NO. :} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label12" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex68 \
        -background white -font TkTextFont -foreground black -height 42 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 295 -wrap word 
    $site_3_0.tex68 configure -font "TkTextFont"
    $site_3_0.tex68 insert end text
    vTcl:DefineAlias "$site_3_0.tex68" "Text2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Validate 
    vTcl:DefineAlias "$site_3_0.but69" "Button3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.362 -y 0 -rely 0.012 -width 0 \
        -relwidth 0.261 -height 0 -relheight 0.031 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex48 \
        -in $site_3_0 -x 0 -relx 0.396 -y 0 -rely 0.097 -width 0 \
        -relwidth 0.201 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.655 -y 0 -rely 0.097 -width 96 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.232 -y 0 -rely 0.097 -width 0 \
        -relwidth 0.123 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.055 -y 0 -rely 0.249 -width 0 \
        -relwidth 0.117 -height 0 -relheight 0.028 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.055 -y 0 -rely 0.314 -width 0 \
        -relwidth 0.117 -height 0 -relheight 0.028 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.39 -width 0 \
        -relwidth 0.117 -height 0 -relheight 0.027 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.055 -y 0 -rely 0.465 -width 0 \
        -relwidth 0.115 -height 0 -relheight 0.028 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.055 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.117 -height 0 -relheight 0.028 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.055 -y 0 -rely 0.678 -width 0 \
        -relwidth 0.115 -height 0 -relheight 0.028 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.546 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.098 -height 0 -relheight 0.027 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.546 -y 0 -rely 0.538 -width 0 \
        -relwidth 0.096 -height 0 -relheight 0.028 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.546 -y 0 -rely 0.689 -width 0 \
        -relwidth 0.098 -height 0 -relheight 0.028 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.055 -y 0 -rely 0.861 -width 0 \
        -relwidth 0.119 -height 0 -relheight 0.029 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but73 \
        -in $site_3_0 -x 0 -relx 0.407 -y 0 -rely 0.938 -width 383 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lis45 \
        -in $site_3_0 -x 0 -relx 0.239 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.201 -height 0 -relheight 0.031 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis46 \
        -in $site_3_0 -x 0 -relx 0.239 -y 0 -rely 0.312 -width 0 \
        -relwidth 0.198 -height 0 -relheight 0.029 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis47 \
        -in $site_3_0 -x 0 -relx 0.239 -y 0 -rely 0.388 -width 0 \
        -relwidth 0.201 -height 0 -relheight 0.03 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis48 \
        -in $site_3_0 -x 0 -relx 0.239 -y 0 -rely 0.463 -width 0 \
        -relwidth 0.201 -height 0 -relheight 0.03 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis49 \
        -in $site_3_0 -x 0 -relx 0.239 -y 0 -rely 0.549 -width 0 \
        -relwidth 0.201 -height 0 -relheight 0.084 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis50 \
        -in $site_3_0 -x 0 -relx 0.239 -y 0 -rely 0.678 -width 0 \
        -relwidth 0.201 -height 0 -relheight 0.039 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis51 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.113 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis52 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.323 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis53 \
        -in $site_3_0 -x 0 -relx 0.839 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.104 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis54 \
        -in $site_3_0 -x 0 -relx 0.839 -y 0 -rely 0.323 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.042 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis55 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.388 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.044 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis56 \
        -in $site_3_0 -x 0 -relx 0.839 -y 0 -rely 0.388 -width 0 \
        -relwidth 0.106 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis57 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.452 -width 0 \
        -relwidth 0.111 -height 0 -relheight 0.042 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis58 \
        -in $site_3_0 -x 0 -relx 0.839 -y 0 -rely 0.452 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis59 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.538 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis60 \
        -in $site_3_0 -x 0 -relx 0.839 -y 0 -rely 0.538 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis61 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.603 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis62 \
        -in $site_3_0 -x 0 -relx 0.839 -y 0 -rely 0.603 -width 0 \
        -relwidth 0.106 -height 0 -relheight 0.041 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis63 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.689 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.03 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad64 \
        -in $site_3_0 -x 0 -relx 0.225 -y 0 -rely 0.861 -width 0 \
        -relwidth 0.169 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad65 \
        -in $site_3_0 -x 0 -relx 0.45 -y 0 -rely 0.861 -width 0 \
        -relwidth 0.162 -height 0 -relheight 0.03 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad66 \
        -in $site_3_0 -x 0 -relx 0.662 -y 0 -rely 0.861 -width 0 \
        -relwidth 0.149 -height 0 -relheight 0.03 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.775 -width 0 \
        -relwidth 0.117 -height 0 -relheight 0.028 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex68 \
        -in $site_3_0 -x 0 -relx 0.239 -y 0 -rely 0.764 -width 0 \
        -relwidth 0.201 -height 0 -relheight 0.045 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 0 -relx 0.484 -y 0 -rely 0.775 -width 96 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.01 -width 0 -relwidth 0.959 \
        -height 0 -relheight 0.98 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

