#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Dec 17, 2020 11:36:29 AM IST  platform: Windows NT
import PIL
import pymongo
from bson import ObjectId
import sys
import mysql.connector
from mysql.connector import Error
from fpdf import FPDF
import tkinter
import tkinter.messagebox as tkMessageBox
from PIL import Image
#import numpy as np
import cv2
import pyautogui
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import student_examform_support
status="failed"

connection=pymongo.MongoClient('localhost', 27017)

database = connection['mydb_01']

collection = database['mycol_01']


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    student_examform_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    student_examform_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def fillform(self):
        try:
            input = self.Text1.get('1.0', 'end')
            try:
                connection = mysql.connector.connect(host='localhost',
                                                     database='aef_database',
                                                     user='root',
                                                     password='toor')
                #sql_select_Query = "select name from student where usn='input'" # sql command q is assign to query variable
                q=("select name from student where usn=")+("'")+input+("'") # to fetch name of student
                sql_select_Query=q
                cursor = connection.cursor()
                cursor.execute(sql_select_Query)
                records = cursor.fetchall()
                self.Listbox11.delete(0, self.Listbox11.size())
                for i in range(0, (cursor.rowcount)):
                    self.Listbox11.insert(i, records[i])
                self.Listbox1.delete(0, self.Listbox1.size())
                self.Listbox1.insert(input)
                q=("select semester from student where usn=")+("'")+input+("'") # to fetch semester of student
                sql_select_Query=q
                cursor = connection.cursor()
                cursor.execute(sql_select_Query)
                records = cursor.fetchall()
                self.Listbox2.delete(0, self.Listbox2.size())
                for i in range(0, (cursor.rowcount)):
                    self.Listbox2.insert(i, records[i])
                q=("select department_dept_name from student where usn=")+("'")+input+("'") # to fetch department of student
                sql_select_Query=q
                cursor = connection.cursor()
                cursor.execute(sql_select_Query)
                records = cursor.fetchall()
                self.Listbox3.delete(0, self.Listbox3.size())
                for i in range(0, (cursor.rowcount)):
                    self.Listbox3.insert(i, records[i])
                q=("select street, city, pincode from student where usn=")+("'")+input+("'") # to fetch address of student
                sql_select_Query=q
                cursor = connection.cursor()
                cursor.execute(sql_select_Query)
                records = cursor.fetchall()
                self.Listbox4.delete(0, self.Listbox4.size())
                for i in range(0, (cursor.rowcount)):
                    self.Listbox4.insert(i, records[i])
                q=("select cgpa from student where usn=")+("'")+input+("'") # to fetch cgpa of student
                sql_select_Query=q
                cursor = connection.cursor()
                cursor.execute(sql_select_Query)
                records = cursor.fetchall()
                self.Listbox5.delete(0, self.Listbox5.size())
                for i in range(0, (cursor.rowcount)):
                    self.Listbox5.insert(i, records[i])
                q=("select course_course_code from opted where student_usn=")+("'")+input+("'") # to fetch COURSES of student
                sql_select_Query=q
                cursor = connection.cursor()
                cursor.execute(sql_select_Query)
                records = cursor.fetchall()
                self.Listbox6.delete(0, self.Listbox6.size())
                self.Listbox7.delete(0, self.Listbox7.size())
                self.Listbox8.delete(0, self.Listbox8.size())
                self.Listbox9.delete(0, self.Listbox9.size())
                self.Listbox10.delete(0, self.Listbox10.size())
                self.Listbox12.delete(0, self.Listbox12.size())
                self.Listbox13.delete(0, self.Listbox13.size())
                self.Listbox14.delete(0, self.Listbox14.size())
                course_list= list()
                for i in range(0, (cursor.rowcount)):
                    course_list.insert(i, records[i])
                    #self.Listbox4.insert(i, records[i])
                self.Listbox6.insert(course_list[0])
                self.Listbox7.insert(course_list[1])
                self.Listbox8.insert(course_list[2])
                self.Listbox9.insert(course_list[3])
                self.Listbox10.insert(course_list[4])
                self.Listbox12.insert(course_list[5])
                self.Listbox13.insert(course_list[6])
                self.Listbox14.insert(course_list[7])
                q=("select lab_course_lcourse_code from taken where student_usn=")+("'")+input+("'") # to fetch COURSES of student
                sql_select_Query=q
                cursor = connection.cursor()
                cursor.execute(sql_select_Query)
                records = cursor.fetchall()
                self.Listbox15.delete(0, self.Listbox15.size())
                self.Listbox16.delete(0, self.Listbox16.size())
                self.Listbox17.delete(0, self.Listbox17.size())
                self.Listbox18.delete(0, self.Listbox18.size())
                lcourse_list= list()
                for i in range(0, (cursor.rowcount)):
                    lcourse_list.insert(i, records[i])
                    #self.Listbox4.insert(i, records[i])
                self.Listbox15.insert(lcourse_list[0])
                self.Listbox16.insert(lcourse_list[1])
                self.Listbox17.insert(lcourse_list[2])
                self.Listbox18.insert(lcourse_list[3])
                #mongoDB code to retrive exam fee and recipt number
                connection=pymongo.MongoClient('localhost', 27017)

                database = connection['mydb_01']

                collection = database['mycol_01']
                 
                mydoc = collection.find({'USN': input}, {'Exam_fee': 1,'_id':0})
                for x in mydoc:
                    exam_fee=x['Exam_fee']
                self.Listbox19.insert(exam_fee)
                
                
            except Exception:
                tkMessageBox.showerror("Error", "Could not reach the server at the movement..please try later..")
            finally:
                if (connection.is_connected()):
                    connection.close()
                    cursor.close()
        except Exception:
            tkMessageBox.showerror("Error", "Please enter your USN...!")
    def Validaterecipt(self):
        try:
            recipt_num = self.Text2.get('1.0', 'end')
            
        except Exception:
            tkMessageBox.showerror("Error", "Please enter valid Recipt Number...!")
        #MongoDB code to retrive recipt id
        connection=pymongo.MongoClient('localhost', 27017)

        database = connection['mydb_01']

        collection = database['mycol_01']
        mydoc= collection.find({'USN': input}, {'Receipt_id': 1,'_id':0})
        for x in mydoc:
            recipt_id=x['Receipt_id']
            
        print(recipt_num)
        print(recipt_id)
       
        
        if(recipt_id != recipt_num):
            tkMessageBox.showerror("Error", " wrong recipt Number ..plese enter correct id")
        else:
            status='success'
            tkMessageBox.showerror("Validation success", " you Can submit the exam form..")

    def submitform(self):
        if(status=='success'):
            image = pyautogui.screenshot()
            image = cv2.cvtColor(np.array(image),
                                 cv2.COLOR_RGB2BGR)

            # writing it to the disk using opencv
            cv2.imwrite("rawimage.png", image)
            im = Image.open('rawimage.png')
            width, height = im.size
            cropped = im.crop((10,(height/4),1800,((3 * height / 4)-18)))
            #Save the cropped image
            cropped.save('exam_registration_form.png')
            #mongoDB code to save this image tomongoDB
            pdf = FPDF()
            # Add a page
            pdf.add_page()
            # set style and size of font that you want in the pdf
            pdf.set_font("Arial", size = 15)
            # create a cell
            pdf.cell(200, 10, txt = "R V College of Engineering", ln = 1, align = 'C')
            # add another cell
            pdf.cell(200, 10, txt = "R V vidyanikethan post Bengalore.", ln = 2, align = 'C')
            pdf.cell(200, 10, txt = "Hallticket", ln = 3, align = 'C')
            pdf.cell(200, 10, txt = "Name : "+name, ln = 3, align = 'C')
            pdf.cell(200, 10, txt = "USN : "+input, ln = 3, align = 'C')
            pdf.cell(200, 10, txt = "semester : "+sem, ln = 3, align = 'C')
            pdf.cell(200, 10, txt = "department : "+dept, ln = 3, align = 'C')
            pdf.cell(200, 10, txt = "Courses Applied", ln = 3, align = 'C')
            pdf.cell(200, 10, txt = course_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = course_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = course_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = course_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = course_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = course_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = course_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = course_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = "Labs Applied", ln = 3, align = 'C')
            pdf.cell(200, 10, txt = lcourse_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = lcourse_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = lcourse_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = lcourse_list[0], ln = 3, align = 'C')
            pdf.cell(200, 10, txt = "Signature of HOD :                                               ", ln = 3, align = 'C')
            pdf.cell(200, 10, txt = "Ramakanth Kumar", ln = 3, align = 'C')
            # save the pdf with name .pdf
            pdf.output("hallticket.pdf")
            tkMessageBox.showerror("success", " Exam form submitted please check your mail for Hallticket")
            #code to send email
        else:
            tkMessageBox.showerror("ERROR", " You have not validated the fee pay recept id..")
    def logoutfun(self):
        exit(0)

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1920x1001+109+16")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Exam form")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.021, rely=0.01, relheight=0.98, relwidth=0.959)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#8080ff")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.362, rely=0.012, height=30, width=481)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#00ff00")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''AUTOMATIC EXAM FORM FILLER''')

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.396, rely=0.097, relheight=0.041, relwidth=0.201)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.655, rely=0.097, height=33, width=96)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(command=self.fillform,text='''FILL FORM''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.232, rely=0.097, height=40, width=227)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#808040")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''ENTER USN :''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.055, rely=0.249, height=28, width=216)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#808040")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''NAME :''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.055, rely=0.314, height=28, width=216)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#808040")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''USN :''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.054, rely=0.39, height=26, width=216)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#808040")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''SEMESTER :''')

        self.Label6 = tk.Label(self.Frame1)
        self.Label6.place(relx=0.055, rely=0.465, height=28, width=212)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#808040")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''DEPARTMENT :''')

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.055, rely=0.552, height=27, width=216)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#808040")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''ADDRESS :''')

        self.Label8 = tk.Label(self.Frame1)
        self.Label8.place(relx=0.055, rely=0.678, height=28, width=212)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#808040")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''CGPA :''')

        self.Label9 = tk.Label(self.Frame1)
        self.Label9.place(relx=0.546, rely=0.248, height=27, width=180)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#808040")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''COURSES :''')

        self.Label10 = tk.Label(self.Frame1)
        self.Label10.place(relx=0.546, rely=0.538, height=27, width=177)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#808040")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''LAB COURSES :''')

        self.Label11 = tk.Label(self.Frame1)
        self.Label11.place(relx=0.546, rely=0.689, height=27, width=180)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(background="#808040")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''EXAM FEE :''')

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.407, rely=0.897, height=43, width=383)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(command=self.submitform,text='''SUBMIT FORM & GENERATE HALL TICKET''')

        self.Listbox11 = tk.Listbox(self.Frame1)
        self.Listbox11.place(relx=0.239, rely=0.248, relheight=0.032
                , relwidth=0.201)
        self.Listbox11.configure(background="white")
        self.Listbox11.configure(disabledforeground="#a3a3a3")
        self.Listbox11.configure(font="TkFixedFont")
        self.Listbox11.configure(foreground="#000000")
        self.Listbox11.configure(highlightbackground="#d9d9d9")
        self.Listbox11.configure(highlightcolor="black")
        self.Listbox11.configure(selectbackground="blue")
        self.Listbox11.configure(selectforeground="white")

        self.Listbox1 = tk.Listbox(self.Frame1)
        self.Listbox1.place(relx=0.239, rely=0.312, relheight=0.03
                , relwidth=0.198)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="black")
        self.Listbox1.configure(selectbackground="blue")
        self.Listbox1.configure(selectforeground="white")

        self.Listbox2 = tk.Listbox(self.Frame1)
        self.Listbox2.place(relx=0.239, rely=0.388, relheight=0.03
                , relwidth=0.201)
        self.Listbox2.configure(background="white")
        self.Listbox2.configure(disabledforeground="#a3a3a3")
        self.Listbox2.configure(font="TkFixedFont")
        self.Listbox2.configure(foreground="#000000")
        self.Listbox2.configure(highlightbackground="#d9d9d9")
        self.Listbox2.configure(highlightcolor="black")
        self.Listbox2.configure(selectbackground="blue")
        self.Listbox2.configure(selectforeground="white")

        self.Listbox3 = tk.Listbox(self.Frame1)
        self.Listbox3.place(relx=0.239, rely=0.463, relheight=0.031
                , relwidth=0.201)
        self.Listbox3.configure(background="white")
        self.Listbox3.configure(disabledforeground="#a3a3a3")
        self.Listbox3.configure(font="TkFixedFont")
        self.Listbox3.configure(foreground="#000000")
        self.Listbox3.configure(highlightbackground="#d9d9d9")
        self.Listbox3.configure(highlightcolor="black")
        self.Listbox3.configure(selectbackground="blue")
        self.Listbox3.configure(selectforeground="white")

        self.Listbox4 = tk.Listbox(self.Frame1)
        self.Listbox4.place(relx=0.239, rely=0.549, relheight=0.084
                , relwidth=0.201)
        self.Listbox4.configure(background="white")
        self.Listbox4.configure(disabledforeground="#a3a3a3")
        self.Listbox4.configure(font="TkFixedFont")
        self.Listbox4.configure(foreground="#000000")
        self.Listbox4.configure(highlightbackground="#d9d9d9")
        self.Listbox4.configure(highlightcolor="black")
        self.Listbox4.configure(selectbackground="blue")
        self.Listbox4.configure(selectforeground="white")

        self.Listbox5 = tk.Listbox(self.Frame1)
        self.Listbox5.place(relx=0.239, rely=0.678, relheight=0.039
                , relwidth=0.201)
        self.Listbox5.configure(background="white")
        self.Listbox5.configure(disabledforeground="#a3a3a3")
        self.Listbox5.configure(font="TkFixedFont")
        self.Listbox5.configure(foreground="#000000")
        self.Listbox5.configure(highlightbackground="#d9d9d9")
        self.Listbox5.configure(highlightcolor="black")
        self.Listbox5.configure(selectbackground="blue")
        self.Listbox5.configure(selectforeground="white")

        self.Listbox6 = tk.Listbox(self.Frame1)
        self.Listbox6.place(relx=0.682, rely=0.248, relheight=0.043
                , relwidth=0.113)
        self.Listbox6.configure(background="white")
        self.Listbox6.configure(disabledforeground="#a3a3a3")
        self.Listbox6.configure(font="TkFixedFont")
        self.Listbox6.configure(foreground="#000000")
        self.Listbox6.configure(highlightbackground="#d9d9d9")
        self.Listbox6.configure(highlightcolor="black")
        self.Listbox6.configure(selectbackground="blue")
        self.Listbox6.configure(selectforeground="white")

        self.Listbox7 = tk.Listbox(self.Frame1)
        self.Listbox7.place(relx=0.682, rely=0.323, relheight=0.043
                , relwidth=0.112)
        self.Listbox7.configure(background="white")
        self.Listbox7.configure(disabledforeground="#a3a3a3")
        self.Listbox7.configure(font="TkFixedFont")
        self.Listbox7.configure(foreground="#000000")
        self.Listbox7.configure(highlightbackground="#d9d9d9")
        self.Listbox7.configure(highlightcolor="black")
        self.Listbox7.configure(selectbackground="blue")
        self.Listbox7.configure(selectforeground="white")

        self.Listbox8 = tk.Listbox(self.Frame1)
        self.Listbox8.place(relx=0.839, rely=0.248, relheight=0.042
                , relwidth=0.104)
        self.Listbox8.configure(background="white")
        self.Listbox8.configure(disabledforeground="#a3a3a3")
        self.Listbox8.configure(font="TkFixedFont")
        self.Listbox8.configure(foreground="#000000")
        self.Listbox8.configure(highlightbackground="#d9d9d9")
        self.Listbox8.configure(highlightcolor="black")
        self.Listbox8.configure(selectbackground="blue")
        self.Listbox8.configure(selectforeground="white")

        self.Listbox9 = tk.Listbox(self.Frame1)
        self.Listbox9.place(relx=0.839, rely=0.323, relheight=0.042
                , relwidth=0.105)
        self.Listbox9.configure(background="white")
        self.Listbox9.configure(disabledforeground="#a3a3a3")
        self.Listbox9.configure(font="TkFixedFont")
        self.Listbox9.configure(foreground="#000000")
        self.Listbox9.configure(highlightbackground="#d9d9d9")
        self.Listbox9.configure(highlightcolor="black")
        self.Listbox9.configure(selectbackground="blue")
        self.Listbox9.configure(selectforeground="white")

        self.Listbox10 = tk.Listbox(self.Frame1)
        self.Listbox10.place(relx=0.682, rely=0.388, relheight=0.044
                , relwidth=0.112)
        self.Listbox10.configure(background="white")
        self.Listbox10.configure(disabledforeground="#a3a3a3")
        self.Listbox10.configure(font="TkFixedFont")
        self.Listbox10.configure(foreground="#000000")
        self.Listbox10.configure(highlightbackground="#d9d9d9")
        self.Listbox10.configure(highlightcolor="black")
        self.Listbox10.configure(selectbackground="blue")
        self.Listbox10.configure(selectforeground="white")

        self.Listbox12 = tk.Listbox(self.Frame1)
        self.Listbox12.place(relx=0.839, rely=0.388, relheight=0.041
                , relwidth=0.106)
        self.Listbox12.configure(background="white")
        self.Listbox12.configure(disabledforeground="#a3a3a3")
        self.Listbox12.configure(font="TkFixedFont")
        self.Listbox12.configure(foreground="#000000")
        self.Listbox12.configure(highlightbackground="#d9d9d9")
        self.Listbox12.configure(highlightcolor="black")
        self.Listbox12.configure(selectbackground="blue")
        self.Listbox12.configure(selectforeground="white")

        self.Listbox13 = tk.Listbox(self.Frame1)
        self.Listbox13.place(relx=0.682, rely=0.452, relheight=0.043
                , relwidth=0.111)
        self.Listbox13.configure(background="white")
        self.Listbox13.configure(disabledforeground="#a3a3a3")
        self.Listbox13.configure(font="TkFixedFont")
        self.Listbox13.configure(foreground="#000000")
        self.Listbox13.configure(highlightbackground="#d9d9d9")
        self.Listbox13.configure(highlightcolor="black")
        self.Listbox13.configure(selectbackground="blue")
        self.Listbox13.configure(selectforeground="white")

        self.Listbox14 = tk.Listbox(self.Frame1)
        self.Listbox14.place(relx=0.839, rely=0.452, relheight=0.042
                , relwidth=0.105)
        self.Listbox14.configure(background="white")
        self.Listbox14.configure(disabledforeground="#a3a3a3")
        self.Listbox14.configure(font="TkFixedFont")
        self.Listbox14.configure(foreground="#000000")
        self.Listbox14.configure(highlightbackground="#d9d9d9")
        self.Listbox14.configure(highlightcolor="black")
        self.Listbox14.configure(selectbackground="blue")
        self.Listbox14.configure(selectforeground="white")

        self.Listbox15 = tk.Listbox(self.Frame1)
        self.Listbox15.place(relx=0.682, rely=0.538, relheight=0.041
                , relwidth=0.112)
        self.Listbox15.configure(background="white")
        self.Listbox15.configure(disabledforeground="#a3a3a3")
        self.Listbox15.configure(font="TkFixedFont")
        self.Listbox15.configure(foreground="#000000")
        self.Listbox15.configure(highlightbackground="#d9d9d9")
        self.Listbox15.configure(highlightcolor="black")
        self.Listbox15.configure(selectbackground="blue")
        self.Listbox15.configure(selectforeground="white")

        self.Listbox16 = tk.Listbox(self.Frame1)
        self.Listbox16.place(relx=0.839, rely=0.538, relheight=0.041
                , relwidth=0.105)
        self.Listbox16.configure(background="white")
        self.Listbox16.configure(disabledforeground="#a3a3a3")
        self.Listbox16.configure(font="TkFixedFont")
        self.Listbox16.configure(foreground="#000000")
        self.Listbox16.configure(highlightbackground="#d9d9d9")
        self.Listbox16.configure(highlightcolor="black")
        self.Listbox16.configure(selectbackground="blue")
        self.Listbox16.configure(selectforeground="white")

        self.Listbox17 = tk.Listbox(self.Frame1)
        self.Listbox17.place(relx=0.682, rely=0.603, relheight=0.041
                , relwidth=0.112)
        self.Listbox17.configure(background="white")
        self.Listbox17.configure(disabledforeground="#a3a3a3")
        self.Listbox17.configure(font="TkFixedFont")
        self.Listbox17.configure(foreground="#000000")
        self.Listbox17.configure(highlightbackground="#d9d9d9")
        self.Listbox17.configure(highlightcolor="black")
        self.Listbox17.configure(selectbackground="blue")
        self.Listbox17.configure(selectforeground="white")

        self.Listbox18 = tk.Listbox(self.Frame1)
        self.Listbox18.place(relx=0.839, rely=0.603, relheight=0.041
                , relwidth=0.106)
        self.Listbox18.configure(background="white")
        self.Listbox18.configure(disabledforeground="#a3a3a3")
        self.Listbox18.configure(font="TkFixedFont")
        self.Listbox18.configure(foreground="#000000")
        self.Listbox18.configure(highlightbackground="#d9d9d9")
        self.Listbox18.configure(highlightcolor="black")
        self.Listbox18.configure(selectbackground="blue")
        self.Listbox18.configure(selectforeground="white")

        self.Listbox19 = tk.Listbox(self.Frame1)
        self.Listbox19.place(relx=0.682, rely=0.689, relheight=0.03
                , relwidth=0.112)
        self.Listbox19.configure(background="white")
        self.Listbox19.configure(disabledforeground="#a3a3a3")
        self.Listbox19.configure(font="TkFixedFont")
        self.Listbox19.configure(foreground="#000000")
        self.Listbox19.configure(highlightbackground="#d9d9d9")
        self.Listbox19.configure(highlightcolor="black")
        self.Listbox19.configure(selectbackground="blue")
        self.Listbox19.configure(selectforeground="white")

        self.Label12 = tk.Label(self.Frame1)
        self.Label12.place(relx=0.054, rely=0.775, height=28, width=216)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#808040")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(text='''Enter Fee Recipt NO. :''')

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.239, rely=0.764, relheight=0.046, relwidth=0.201)

        self.Text2.configure(background="white")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="blue")
        self.Text2.configure(selectforeground="white")
        self.Text2.configure(wrap="word")

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.484, rely=0.775, height=33, width=96)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(command=self.Validaterecipt,text='''Validate''')

        self.logoutbtn = tk.Button(self.Frame1)
        self.logoutbtn.place(relx=0.9, rely=0.022, height=33, width=99)
        self.logoutbtn.configure(activebackground="#ececec")
        self.logoutbtn.configure(activeforeground="#000000")
        self.logoutbtn.configure(background="#d9d9d9")
        self.logoutbtn.configure(disabledforeground="#a3a3a3")
        self.logoutbtn.configure(foreground="#000000")
        self.logoutbtn.configure(highlightbackground="#d9d9d9")
        self.logoutbtn.configure(highlightcolor="black")
        self.logoutbtn.configure(pady="0")
        self.logoutbtn.configure(command=self.logoutfun,text='''LOGOUT''')

if __name__ == '__main__':
    vp_start_gui()
